name: app
description: A cross-platform lyric browsing and playback experience.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_hooks: ^0.20.5
  audioplayers: ^5.2.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.18.0
  google_fonts: ^6.1.0
  http: ^1.2.1
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/lyrics.json
